name: Print logs
inputs:
  files:
    description: Files to print.
    required: true
  working-directory:
    description: Working directory.
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
  - name: Print files
    env:
      wds: ${{ inputs.working-directory }}
      files: ${{ inputs.files }}
    shell: bash
    run: |
      set +e

      for wd in $wds; do
        for file in $files; do
          for log in `find $wd -type f -name '$file'`; do
            if [ -f "$log" ]; then
              echo -e ::group::File: $log
              cat $log
              echo ::endgroup::
            fi
          done
        done
      done

      exit 0
